modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="betterwaystonesmenu"
version="${version}"
displayName="BetterWaystonesMenu"
logoFile="betterwaystonesmenu-icon.png"
authors="Loxoz"
description='''
Enhances the Waystones' mod selection menu
'''

[[dependencies.betterwaystonesmenu]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.betterwaystonesmenu]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,1.20)"
   ordering="NONE"
   side="BOTH"
[[dependencies.betterwaystonesmenu]]
    modId="waystones"
    mandatory=true
    versionRange="[11.4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterwaystonesmenu]]
    modId="balm"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"
